# Uncomment the next line to define a global platform for your project
# Use iOS 9 and above
platform :ios, '9.0'

target 'reduxDemo' do
  pod 'Stripe', '~> 13.2.0'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'



end
