# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reduxDemo' do
  # pod 'Stripe', '~> 9.2.0'
  # inherit! :search_paths
  pod 'Firebase'
  pod 'Firebase/Messaging'
end
